language: node_js
before_install:
- chmod +x ./scripts -R
node_js:
- '4.3'
deploy:
  skip_cleanup: true
  provider: npm
  email: luke@chavers.io
  api_key:
    secure: uTWbVRnslFbNl3BNjeVNMT3QziPeWP41X6abS+xGQGD0+0X/kSkvXdtHh4k2DRX7m3NszI4JLaFx+aSXllVzOhhwBbvs9WNJExWAg2YhacbgG8Bcjqhnw8rAcYDNombn/6TR2xI/Qb/8G7WMoA/nAVe4kKWU+68KcTNDGYVBSsQV20+2sfU8KtVjLq6/ReIuESdd/BdYxbAYunSvQrrk5oiA0iYzTLMZNmMEpzpwCx8jVMjHww2fJ/dZVy0agPLgr9Zqf3SJwK/K5yQFV7fvtj5UFTq3L3BrlweK09/Ah7lfAa5/0isSLQspVIaVSWC2znP7RA2dAIKxfOyWxkxCGBSfjXs/1rM5lPFspEUbzkwUoDaGmjLlHqIxb+8EyY2OT3eCH1K1ngCqi1D+GjqNhQneEx1amfNdjPYnXpavwuarbDdUn8+zV18QEVNxWzIm1TWfB+f1jeEQ19fw7eDzbnDK4DwjMfddWIfhSjcubBaHT9i3bwAOipUlc2onSRxZezZT0p+9o1HoLNd2wMk9uI3BL4GPG6m14AkbHH9QqoSU178uHzruPAlSlerGKWk3uMp+3heZ9I9XNnfpCdnmA4icRVfnUiavF3bcsYpHDvR8away9RkCeb8f+wLycMDUgU/b3OjP14GZlybDOxaAW1qvuIdCB/YeE4mSxHC6i7c=
  on:
    repo: Dasix/grits-plugin-pdf
